src/Entity/Trainee.php
<?php

namespace App\Entity;

use App\Repository\TraineeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TraineeRepository::class)
 */
class Trainee
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $numberPoleEmploi;

    /**
     * @ORM\ManyToMany(targetEntity=Session::class, mappedBy="trainees")
     */
    private $sessions;
    
    public function __toString()
    {
        return $this->firstName." ".strtoupper($this->lastName);
    }

    public function getFullAdress()
    {
        return $this->adress." ".$this->postalCode." ".$this->city;
    }

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getNumberPoleEmploi(): ?string
    {
        return $this->numberPoleEmploi;
    }

    public function setNumberPoleEmploi(?string $numberPoleEmploi): self
    {
        $this->numberPoleEmploi = $numberPoleEmploi;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addTrainee($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->removeElement($session)) {
            $session->removeTrainee($this);
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Trainee;
use App\Entity\Location;
use App\Form\TraineeType;
use App\Form\TraineeSassionType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="accueil")
     */
    public function index(): Response
    {
        $sessionRepository = $this->getDoctrine()->getRepository(Session::class);
        $sessions = $sessionRepository->findNextThree();
        $nbsessions = $sessionRepository->countSessions();
     
        $nbtrainees = $this->getDoctrine()->getRepository(Trainee::class)->countTrainees();
        $nblocations = $this->getDoctrine()->getRepository(Location::class)->countLocations();

        return $this->render('main/index.html.twig', [
            'sessions' => $sessions,
            'nbsessions' => $nbsessions,
            'nbtrainees' => $nbtrainees,
            'nblocations' => $nblocations
        ]);
    }

    /**
     * @Route("/stagiaires", name="stagiaires")
     */
    public function stagiaires(Trainee $trainee = NULL, Request $request): Response
    {
        $stagiaireRepository = $this->getDoctrine()->getRepository(Trainee::class);
    
        if (!$trainee) {
            $trainee = new Trainee();
        }

        $form = $this->createForm(TraineeType::class, $trainee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trainee = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($trainee);
            $entityManager->flush();

            return $this->redirectToRoute('stagiaires');
        }


        $stagiaires = $stagiaireRepository->findBy([], ["lastName" => "ASC"]);
        return $this->render('main/stagiaires.html.twig', [
            'formTrainee' => $form->createView(),
            'stagiaires' => $stagiaires
        ]);
    }
    
    /**
     * @Route("/showStagiaire/{id}", name="show_stagiaire")
     */
    public function showTrainee(Trainee $trainee= null, Request $request): Response
    {

        $form = $this->createForm(TraineeSassionType::class, $trainee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            return $this->redirectToRoute('show_stagiaire',["id"=>$trainee->getId()]);
        }

        return $this->render('main/showStagiaire.html.twig', [
            'formTrainee' => $form->createView(),
            'stagiaire' => $trainee,
        ]);
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}


<h3>Les 3 prochaines sessions</h3>
<table class='uk-table uk-table-hover uk-table-divider'>
    <thead>
        <tr>
            <th>Session</th>
            <th>Nb de stagiaires inscrit</th>
            <th>Nb de stagiaires minimum</th>
            <th>Nb de stagiaires maximum</th>
            <th>Lieu</th>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for session in sessions %}          
            <tr>
                <td>
                    <a href="{{ path('show_session', {id:session.id} ) }}">
                        {{ session.title }}
                    </a>
                </td>
                <td>{{ session.trainees|length }}</td>
                <td>{{ session.minimumTrainees }}</td>
                <td>{{ session.maximumTrainees }}</td>                  
                <td>{{ session.location }}</td>
                <td>{{ session.startDate| date('d/m/Y') }}</td>
                <td>{{ session.endDate| date('d/m/Y') }}</td>
                <td>
                    <!-- https://getuikit.com/docs/icon -->
                    <a class="uk-icon-link uk-margin-small-right" uk-icon="file-edit" href="#"></a>
                    <a class="uk-icon-link" uk-icon="trash" href=""></a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div id="home-numbers" class="uk-flex uk-flex-center">
    <div class="uk-card uk-card-default uk-card-body uk-text-center">
        <p class="numbers">{{ nbtrainees }}</p>
        <p class="under-number">Stagiaires</p>                
    </div>
    <div class="uk-card uk-card-default uk-card-body uk-margin-left uk-text-center">
        <p class="numbers">{{ nblocations }}</p>
        <p class="under-number">Lieux</p>                    
    </div>
    <div class="uk-card uk-card-default uk-card-body uk-margin-left uk-text-center">
        <p class="numbers">{{ nbsessions }}</p>
        <p class="under-number">Sessions de formation</p>  
    </div>
</div>

{% endblock %}

templates/main/showStagiaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ stagiaire }}
{% endblock %}

{% block body %}
<h1>{{ stagiaire }}</h1>
<table class='uk-table uk-table-hover uk-table-divider'>
		<tr>
			<th>Prénom NOM</th>
			<td>{{ stagiaire }}</td>
		</tr>
		<tr>
			<th>Adress</th>
			<td>{{ stagiaire.fullAdress }}</td>
		</tr>
		<tr>
			<th>Téléphone</th>
			<td>{{ stagiaire.phone }}</td>
		</tr>
		<tr>
			<th>Nb Pole Emploi</th>
			<td>{{ stagiaire.numberPoleEmploi }}</td>
		</tr>
		<tr>
			<th>Session(s)</th>
			<td>
				{% for session in stagiaire.sessions %}          
					<p> {{ session.title ~ ", " ~ session.training.title ~ " (" ~ session.startDate| date('d/m/Y') ~ " - " ~ session.endDate| date('d/m/Y') ~")" }}</p>
				{% endfor %}				
			</td>				
		</tr>
		<tr>
			<th>Action</th>
			<td>
				<!-- https://getuikit.com/docs/icon -->
				<a class="uk-icon-link uk-margin-small-right" uk-icon="file-edit" href="#"></a>
				{% if is_granted('ROLE_ADMIN') %}
					<a class="uk-icon-link" uk-icon="trash" href=""></a>
				{% endif %}
			</td>
		</tr>
</table>
<h1>Sessions</h1>
{{ form(formTrainee) }}
{% endblock %}

templates/main/stagiaires.html.twig
{% extends 'base.html.twig' %}



{% block title %}Liste des stagiaires
{% endblock %}

{% block body %}

<h1>Ajouter un stagiaire</h1>
{{ form(formTrainee) }}

	<h1>Liste des stagiaires</h1>
	<table class='uk-table uk-table-hover uk-table-divider'>
		<thead>
			<tr>
				<th>Prénom NOM</th>
				<th>Adress</th>
				<th>Téléphone</th>
				<th>Nb Pole Emploi</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for stagiaire in stagiaires %}
				<tr>
					<td>
                        <a href="{{ path('show_stagiaire', {id:stagiaire.id} ) }}">
                            {{ stagiaire }}
                        </a>                    
                    </td>
					<td>{{ stagiaire.fullAdress }}</td>
					<td>{{ stagiaire.phone }}</td>
					<td>{{ stagiaire.numberPoleEmploi }}</td>
					<td>
						<!-- https://getuikit.com/docs/icon -->
						<a class="uk-icon-link uk-margin-small-right" uk-icon="file-edit" href="#"></a>
						{% if is_granted('ROLE_ADMIN') %}
							<a class="uk-icon-link" uk-icon="trash" href=""></a>
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}